version: "3.10"

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT={ip-address}:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://{ip-address}:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
